version: '3.8'

services:
  redis:
    image: redis:6.2.14
    container_name: backend-redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  mysql:
    image: mysql:8.0
    container_name: backend-mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql # 使用 Docker 卷
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

volumes:
  redis-data:
  mysql-data:
